available_text_models:
  - gpt-4o
  - gpt-4o-2024-08-06
  - gpt-4o-mini
  # - o1-preview
  # - o1-mini

available_image_reasoning_models:
  - gpt-4o
  - gpt-4o-2024-08-06

default_model: gpt-4o-2024-08-06

info:
  gpt-4o:
    type: chat_completion
    name: GPT-4o
    description: GPT-4o is our most advanced model, offering high intelligence and efficiency for complex tasks. It is multimodal and excels in non-English languages.
    price_per_1M_input_tokens: 5.00
    price_per_1M_output_tokens: 15.00
    scores:
      Smart: 4
      Fast: 3
      Cheap: 1

  gpt-4o-2024-08-06:
    type: chat_completion
    name: GPT-4o Snapshot
    description: The latest snapshot supporting Structured Outputs. Provides high intelligence and efficiency for multi-step tasks.
    price_per_1M_input_tokens: 2.50
    price_per_1M_output_tokens: 10.00
    scores:
      Smart: 4
      Fast: 3
      Cheap: 2

  gpt-4o-mini:
    type: chat_completion
    name: GPT-4o Mini
    description: GPT-4o Mini is an affordable and intelligent small model for fast, lightweight tasks. Cheaper and more capable than GPT-3.5 Turbo.
    price_per_1M_input_tokens: $0.150
    price_per_1M_output_tokens: $0.600
    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  # o1-preview:
  #   type: chat_completion
  #   name: o1-preview
  #   description: The reasoning model designed to solve complex problems across domains. Requires thorough internal thought process before responding.
  #   price_per_1M_input_tokens: 15.00
  #   price_per_1M_output_tokens: 60.00
  #   scores:
  #     Smart: 5
  #     Fast: 2
  #     Cheap: 1

  # o1-mini:
  #   type: chat_completion
  #   name: o1-mini
  #   description: A faster and cheaper reasoning model particularly suitable for coding, math, and science tasks.
  #   price_per_1M_input_tokens: 3.00
  #   price_per_1M_output_tokens: 12.00
  #   scores:
  #     Smart: 4
  #     Fast: 3
  #     Cheap: 3

  dalle-3:
     type: image
     price_per_1_image: 0.04  # Standard 1024×1024

  whisper:
    type: audio
    price_per_1_min: 0.006
